site_name: TBIA Documentations 公開文件
nav:
  #- Getting Started: index.md
  #- Full Example: example.md
  #- Try Try See: trytrysee.md
  - 指引與模板:
    - TBIA文件指引: document_guidelines.md
    - TBIA文件模板: document_template.md
  - 公開文件:
    - 臺灣生物多樣性資訊聯盟章程: articles_of_association.md
    - TBIA共同願景: alliance_vision.md
    - TBIA臺灣生物多樣性資訊聯盟單位狀況自評表（正式會員加盟使用）(in progress): partnership.md
    - TBIA臺灣生物多樣性資訊聯盟單位狀況自評表（合作夥伴加盟使用）(in progress): collaborate.md
    - 生物多樣性領域資料標準: biodiversity_data_standard.md
    - 生物多樣性敏感資料開放作業原則: restricted_access_species_data.md
    - TBIA資料空缺概況整理文件(in progress): datagap.md
  # - 測試(playing in chaos):
  #   - 來寫作業囉: 來寫作業囉.md
  #   - 暑假作業: 暑假最後一天才在寫暑期作業的me.md
  #   - 語法測試: index-test.md
  #- 文件模板的作業:
  #- 文件指引的作業:
theme:
  name: 'material'
  logo: assets/logo_top.svg
  favicon: assets/favicon-32x32.png
  palette:
    primary: custom
  custom_dir: overrides

plugins:
  - search
  - git-authors
  - git-committers
  - git-revision-date:
      as_datetime: True
  - macros
  # - mkdocs-jupyter:
  #     ignore_h1_titles: True
  #     show_input: True
  #     no_input: False
  #     execute: True
  #     allow_errors: False
  #     kernel_name: python3
  #     highlight_extra_classes: "custom-css-classes"
  #     include_requirejs: True
  #     include_source: True
  #- pdf-export:
  #    combined: true
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - footnotes
  - attr_list
  - md_in_html
  - admonition
extra_css:
  - stylesheets/extra.css
