site_name: TBIA Documentations 公開文件
nav:
  - Getting Started: index.md
  - Full Example: example.md
  - Try Try See: trytrysee.md
  - 試做:
    - 敏感資料開放作業原則試做: 敏感資料開放作業原則試做.md
    - TBIA 共同願景試做: TBIA 共同願景（草案）.md
    - 文件指引草稿: TBIA 文件 Guidelines（草稿）.md
    - 文件模板本體: TBIA 文件模板（草稿）.md
  - 寫作業:
    - 來寫作業囉: 來寫作業囉.md
    - 暑假作業: 暑假最後一天才在寫暑期作業的me.md
  #- 文件模板的作業:
  #- 文件指引的作業:
theme:
  name: 'material'
  logo: assets/logo_top.svg
  favicon: assets/favicon-32x32.png
  palette:
    primary: 'green'
  custom_dir: overrides

plugins:
  - search
  - git-authors
  - git-committers
  - git-revision-date:
      as_datetime: True
  - macros
  #- pdf-export:
  #    combined: true
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
