site_name: TBIA Docs
nav:
  - Getting Started: index.md
  - Full Example: example.md
  - Try Try See: trytrysee.md
  - 敏感資料: 生物多樣性敏感資料開放作業原則 by 俊怡.md
theme:
   name: 'material'
   palette:
        primary: 'green'
