site_name: TBIA Documentations 公開文件
nav:
  #- Getting Started: index.md
  #- Full Example: example.md
  #- Try Try See: trytrysee.md
  - 指引與模板(in progress):
    - TBIA文件指引(in progress): TBIA 文件指引 Guidelines（草稿）.md
    - TBIA文件模板(in progress): TBIA 文件模板（草稿）.md
  - 公開文件(in progress):
    - TBIA組織章程(in progress): tbia_articles_of_association.md
    - TBIA共同願景(in progress): TBIA 共同願景（草案）.md
    - 生物多樣性領域資料標準(in progress): biodiversity_data_standard.md
    - 生物多樣性敏感資料開放作業原則(in progress): 敏感資料開放作業原則試做.md
  - 測試(playing in chaos):
    - 來寫作業囉: 來寫作業囉.md
    - 暑假作業: 暑假最後一天才在寫暑期作業的me.md
    - 語法測試: index-test.md
  #- 文件模板的作業:
  #- 文件指引的作業:
theme:
  name: 'material'
  logo: assets/logo_top.svg
  favicon: assets/favicon-32x32.png
  palette:
    primary: custom
  custom_dir: overrides

plugins:
  - search
  - git-authors
  - git-committers
  - git-revision-date:
      as_datetime: True
  - macros
  #- pdf-export:
  #    combined: true
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - attr_list
  - md_in_html
  - admonition
extra_css:
  - stylesheets/extra.css
