site_name: TBIA Docs
nav:
  - Getting Started: index.md
  - Full Example: example.md
  - Try Try See: trytrysee.md
  - 寫作業:
    - 敏感資料: 生物多樣性敏感資料開放作業原則 by 俊怡.md
    - 來寫作業囉: 來寫作業囉.md
    - 暑假作業: 暑假最後一天才在寫暑期作業的me.md
  - 文件模板的作業:
    - 文件模板本體: TBIA 文件模板（草稿）.md
    - 敏感資料開放作業原則試做: 敏感資料開放作業原則試做.md
  - 文件指引的作業:
    - 文件指引草稿: TBIA 文件 Guidelines（草稿）.md
theme:
  name: 'material'
  palette:
    primary: 'green'
  custom_dir: overrides

plugins:
  - search
  - git-authors
  - git-committers
  - git-revision-date:
      as_datetime: True
  - macros
  #- pdf-export:
  #    combined: true
